language: r
sudo: required
cache: packages

warnings_are_errors: false

r_github_packages:
  - jimhester/covr

before_install:
  - docker run -d -p 5984:5984 klaemo/couchdb:2.0-rc2 --with-haproxy

before_script:
  - curl -X PUT localhost:5984/testing123

services:
  - docker

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: dL3psgn7DJW3fz1no7OMlB3Bm4cOI789RInUBiB04W0cxsjWSYiPcYrvNr8nYAEMWnpqnQDq0G/c2emzoWQoY0frZda69mH147pbjBsWrTic5FMoKxTe7l4PP2YNk5fYxJKw9bF9CTXNxQunfvxWRUHTri7oxBCnMqp5zAyckZ8=
